import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

const pkgPath = path.join(rootDir, 'package.json');
const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
const version = pkg.version;
const now = Date.now();
const iso = new Date(now).toISOString();

// 1. Update public/version.json
const publicVersionPath = path.join(rootDir, 'public', 'version.json');
let publicVersionData = {
  features: [
    "Over-the-air automatic updates for Desktop and Staff Mobile apps",
    "Real-time GPS geofence matching (50m radius) with live distance indicator",
    "Compass heading HUD and permanent watermark with site data",
    "Multi-Slot Date Range Booking Engine with Conflict Prevention"
  ]
};

if (fs.existsSync(publicVersionPath)) {
  try {
    const existing = JSON.parse(fs.readFileSync(publicVersionPath, 'utf-8'));
    if (existing.features && Array.isArray(existing.features)) {
      publicVersionData.features = existing.features;
    }
  } catch (e) {}
}

publicVersionData.version = version;
publicVersionData.buildTimestamp = now;
publicVersionData.buildDate = iso;
publicVersionData.releaseTag = `v${version}`;
publicVersionData.apkUrl = 'https://github.com/kamleshgupta905/Hoarding/releases/download/staff-apk-latest/heera-staff-camera.apk';

fs.writeFileSync(publicVersionPath, JSON.stringify(publicVersionData, null, 2) + '\n', 'utf-8');
console.log(`[sync-version] Updated public/version.json -> v${version} (${now})`);

// 2. Update src/version.js
const srcVersionPath = path.join(rootDir, 'src', 'version.js');
const srcContent = `// 🚀 Current Build Version & Timestamp (Auto-generated by scripts/sync-version.js)
export const APP_VERSION = "${version}";
export const APP_BUILD_TIMESTAMP = ${now};
export const APP_BUILD_DATE = "${iso}";
export const UPDATE_CHECK_URL = "https://hoarding-hd9a.vercel.app/version.json";
`;
fs.writeFileSync(srcVersionPath, srcContent, 'utf-8');
console.log(`[sync-version] Updated src/version.js -> v${version} (${now})`);
