// 🚀 Current Build Version & Timestamp (Auto-generated by scripts/sync-version.js)
export const APP_VERSION = "1.6.0";
export const APP_BUILD_TIMESTAMP = 1789216175720;
export const APP_BUILD_DATE = "2026-09-12T12:29:35.720Z";
export const UPDATE_CHECK_URL = "https://hoarding-hd9a.vercel.app/version.json";
