// 🚀 Current Build Version & Timestamp (Auto-generated by scripts/sync-version.js)
export const APP_VERSION = "1.6.0";
export const APP_BUILD_TIMESTAMP = 1788953098244;
export const APP_BUILD_DATE = "2026-09-09T11:24:58.244Z";
export const UPDATE_CHECK_URL = "https://hoarding-hd9a.vercel.app/version.json";
